name: Contact Service CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_LOCAL_URI: mongodb://localhost/resthub
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "4.2"

      - name: Install dependencies and test
        working-directory: ./contact-service
        run: |
          npm ci
          npm run build --if-present
          npm test
